### ISSUE TITLE
preserve:true for block- and inline-size

### ISSUE THREAD

**Issue by davidf03** [jonathantneal/postcss-logical#10]
`preserve: true` with `block-size` and `inline-size` doesn't seem to work.

**Comment by jonathantneal** [comment]
I will look into this. Could you draw up a failing test?

**Comment by davidf03** [comment]
How do I do that? I'm not too familiar with this process, but happy to help

**Comment by ahmadalfy** [comment]
@dfriesen1183 I think what @jonathantneal means state what you tried and why it didn't work and what did you expect. It could be a problem in the syntax you used.

**Comment by jonathantneal** [comment]
I need to close this due to inactivity, but if you can provide some working code then I will look into it again.

**Comment by Josh68** [comment]
@jonathantneal, I'd like to see if this should be re-opened, or if I am using it or interpreting the docs incorrectly. In our project, I am using with `postcss-preset-env`, configured as follows:

```
require('postcss-preset-env')({
    features: {
      'logical-properties-and-values': {
        preserve: true,
      },
    },
  }),
```
and
```
> 2%
last 1 safari version
last 1 ios version
last 1 firefox version
last 1 chromeandroid version
```

If I have source like this:

```
.some-selector {
  margin-block-start: 10px !important;
  margin-inline-start: 10px !important;
}
```
the resulting CSS is
```
[dir="ltr"] .some-selector {
  margin-left: 10px !important; // Directional output nested, conditioned by `dir` attribute
}
.some-selector {
  margin-top: 10px !important; // Directional output, only
  margin-inline-start: 10px !important; // Logical output (preserved)
}
```
I may be confused, but should I expect to always see logical properties in my output (preserved), as well as directional properties as fallbacks?

https://github.com/csstools/postcss-logical#preserve

Thank you

**Comment by jonathantneal** [comment]
This sounds like a bug. Any chance someone can add a test to reproduce this?

**Comment by Josh68** [comment]
> This sounds like a bug. Any chance someone can add a test to reproduce this?

Thank you. I'm not sure I'm up to the task of writing a test for this, but I'll have a closer look.

**Comment by jonathantneal** [comment]
@Josh68, I’m happy to help find an easier way to write tests. Here is what I recommend.

1. To begin; [fork this project](https://github.com/csstools/postcss-logical/fork), clone your fork, and add our upstream.
   ```bash
   # Clone your fork of the repo into the current directory
   git clone git@github.com:Josh68/postcss-logical-properties.git

   # Navigate to the newly cloned directory
   cd postcss-logical-properties

   # Assign the original repo to a remote called "upstream"
   git remote add upstream git@github.com:csstools/postcss-logical-properties.git

   # Install the tools necessary for testing
   npm install
   ```

2. Create a branch for your test:
   ```bash
   # Move into a new branch for your test
   git checkout -b test/preserve-option-bug
   ```
3. Add a `preserve` test to `.tape.js`, create a `test/preserve.css` file, then push your branch:
   ```js
   module.exports = {
   	preserve: {
   		message: 'fails preserve option',
   		options: {
   			preserve: false
   		}
   	}
   }
   ```
   ```css
   .some-selector {
     margin-block-start: 10px !important;
     margin-inline-start: 10px !important;
   }
   ```
   ```bash
   # Push the branch for your new test
   git push origin test/preserve-option-bug
   ```

Then share the link here.

[fork this project]:     fork

**Comment by jonathantneal** [comment]
For what it’s worth, I think those steps are way too complicated, and I totally understand if that’s too much. When I have the time, I really have to make this easier. I am so sorry about that.

**Comment by Josh68** [comment]
> 
> 
> For what it’s worth, I think those steps are way too complicated, and I totally understand if that’s too much. When I have the time, I really have to make this easier. I am so sorry about that.

No problem, @jonathantneal. I had already cloned the project and looked at adding a test, but realized I needed a full understanding of what kinds of inputs and outputs made sense for it to be meaningful. I'll take a closer look and see if I can contribute something.

**Comment by Josh68** [comment]
@jonathantneal, I'm looking at what's already in tests, and it seems to me that what might be needed is additional blocks something like this, to match the `border: preserve` test:
```js
'margin:preserve': {
		message: 'fails logical "margin" property values with { preserve: true }',
		options: {
			preserve: false,
		},
	},
```
and
```
'padding:preserve': {
		message: 'fails logical "padding" property values with { preserve: true }',
		options: {
			preserve: false,
		},
	},
```
... except I'm not clear on why it should be `preserve: false`.

I see that running tests now produces two new "result" files, which are missing "expect" files, against which the module could be tested.

The other thing that's not clear to me is how you test against code that has one or more of (directional and writing-mode examples)

- [dir="ltr"]
- style="direction: ltr;"
- style="writing-mode: vertical-lr"

---

If what you specified is exactly what you want, however, I'm fine with contributing that. I just seems that specific test cases for the `preserve: true` option are missing.

Thanks
