### ISSUE TITLE
Border-radius properties

### ISSUE THREAD

**Issue by davidf03** [jonathantneal/postcss-logical#11]
Is there any plan to continue support for incoming properties, like `border-[start|end]-[start|end]-radius`?

**Comment by jonathantneal** [comment]
If there’s a spec for them, then yes.

**Comment by ahmadalfy** [comment]
@jonathantneal I think it is still a [draft](https://drafts.csswg.org/css-logical/#border-radius-properties).

**Comment by sheff146** [comment]
Hey guys! I've submitted a [pull request](https://github.com/jonathantneal/postcss-logical/pull/12) for this issue. Please take a look.

**Comment by jonathantneal** [comment]
Resolved by #12
