### ISSUE TITLE
Physical properties

### ISSUE THREAD

**Issue by pavlomatchak** [jonathantneal/postcss-logical#13]
Hi. Thank you for a great work. I have a question about plugin. Does it converts physical properties for both directions? For example float: right into float: left. Or it's only for logical properties?

Thank you, Pasha

**Comment by ahmadalfy** [comment]
It only works on logical properties and values.

**Comment by jonathantneal** [comment]
That’s correct. Consider [rtlcss](https://rtlcss.com/) for something sugary. This only implements what the spec defines.
