### ISSUE TITLE
Incorrect logical sizing in v4

### ISSUE THREAD

**Issue by paulrobertlloyd** [jonathantneal/postcss-logical#17]
Hi Jonathan,

Having upgraded to v4 of this plugin, I noticed that parts of my layout broke. Looking into why, it seems that the logical sizing properties have been reversed. From my limited testing, I have observed the following:

Value | v3.0.0 | v4.0.0
-|-|-
`block-size` | `height` | `width`
`inline-size` | `width` | `height`

In addition, min/max values are no longer translated into their physical equivalents (assuming left-to-right, top-to-bottom):

Value | v3.0.0 | v4.0.0
-|-|-
`min-block-size` | `min-height` | `min-block-size`
`max-block-size` | `max-height` | `max-block-size`
`min-inline-size` | `min-width` | `min-inline-size`
`max-inline-size` | `max-width` | `max-inline-size`

Other properties don’t appear to be affected.

**Comment by jonathantneal** [comment]
Thanks @paulrobertlloyd for reporting this. I’ve updated tests, fixed the issue, and published the fix in 4.0.2. Thank you so much, and I’m sorry for breaking your builds.

**Comment by paulrobertlloyd** [comment]
Thanks so much for the quick fix, @jonathantneal. No apology needed; you’re doing great work here, and it’s much appreciated. 👍
