### ISSUE TITLE
Consider adding support for overflow and overscroll-behavior

### ISSUE THREAD

**Issue by majido** [jonathantneal/postcss-logical#18]
There is specification for logical version of `overflow` and `overscroll-behavior`:
- overflow-inline
- overflow-block
- overscroll-behavior-inline
- overscroll-behavior-block

Chrome should relatively soon get support for both (See [1](https://chromium-review.googlesource.com/c/chromium/src/+/1626428) and [2](https://chromium-review.googlesource.com/c/chromium/src/+/1614026)). Just to be clear these are not yet shipped in Chrome so I don't suggest adding the support yet.

But just wanted to given you a heads up since I think it will be nice if your plugin could support them as well once these are available in Chrome.

**Comment by ahmadalfy** [comment]
I could only find it [here](https://drafts.csswg.org/mediaqueries-4/#mf-overflow-inline) as a part of the media queries level 4 specification and not as a part of the logical properties / values. What exactly is needed from the plugin to work in your opinion? `inline` and `block` here refers to the x and y axis as far as I understand

**Comment by majido** [comment]
Below are the links to relevant sections for each one:
 - https://drafts.csswg.org/css-overflow/#logical
 - https://drafts.csswg.org/css-overscroll/#overscroll-behavior-longhands-logical

I believe going forward logical properties will be added as part of their own relevant specification as opposed to being part of "Logical Properties" spec. See [here](https://drafts.csswg.org/css-logical-1/#intro): 

> Future CSS specifications are expected to incorporate both sets of coordinates in their property and value definitions, so this module will not track the introduction of flow-relative variants of newer CSS features.





You are correct. In both cases `inline` and `block` map to `x` and `y` according to writing mode and direction. FWIW my interpretation of this mapping is captured in this [test](https://chromium-review.googlesource.com/c/chromium/src/+/1614026/7/third_party/blink/web_tests/external/wpt/css/css-overscroll-behavior/overscroll-behavior-logical.html)

**Comment by Antonio-Laguna** [comment]
This repository is getting archived. If this issue keeps happening please re-open on [@csstools/postcss-plugins](https://github.com/csstools/postcss-plugins/issues/new/choose) and we'll do our best to fix it!
