### ISSUE TITLE
Integrating with Vue CLI 3 tool

### ISSUE THREAD

**Issue by rondymesquita** [jonathantneal/postcss-logical#22]
Is there any example of how to integrate with Vue CLI 3?
I have a `postcss.config.js` and a `vue.config.js` but I tried some changes but I could not make it work.

My last change was on `postcss.config.js`
```
module.exports = {
  plugins: [
    autoprefixer(), //already existing on my project.
    postcssLogical()
  ]
}
```

**Comment by ahmadalfy** [comment]
This is my config file:

```javascript
module.exports = {
  plugins: {
    'postcss-logical': {},
    'postcss-dir-pseudo-class': {},
  }
};
```

Btw you need `postcss-dir-pseudo-class` as well.

**Comment by rondymesquita** [comment]
I'm going to try this!

**Comment by rondymesquita** [comment]
No success. :(

**Comment by rondymesquita** [comment]
Is there any configuration on your `vue.config.js` file?

**Comment by y-a-ava** [comment]
this worked for me, hope it helps:


const postcssLogical = require('postcss-logical')
...
  css: {
    loaderOptions: {
      postcss: {
        plugins: [postcssLogical]
      }
    },
  },
