### ISSUE TITLE
does not work well with postcss-modules

### ISSUE THREAD

**Issue by jngbng** [jonathantneal/postcss-logical#25]
https://github.com/css-modules/postcss-modules/issues/104

Just to inform you about the above issue. I do not know yet which module has a problem.

**Comment by ahmadalfy** [comment]
I think this is related to the order of PostCSS plugins. I never used CSS Modules but from the way I see they will transform the class name you write. Currently postcss-logical will add `dir` pseudo selector before your selector so it's no longer a so it becomes a combined selector.

**Comment by Antonio-Laguna** [comment]
This repository is getting archived. If this issue keeps happening please re-open on [@csstools/postcss-plugins](https://github.com/csstools/postcss-plugins/issues/new/choose) and we'll do our best to fix it!
