### ISSUE TITLE
Could not parse rotation with a decimal

### ISSUE THREAD

**Issue by GarthDB** [jonathantneal/postcss-logical#28]
Using `transform: rotate(72.3deg);` results in the following error:

`postcss-transform-logical: could not parse rotate(72.3deg)`

**Comment by romainmenke** [comment]
I think this is resolved (but probably not yet released).
I can't reproduce it on the main branch.

**Comment by romainmenke** [comment]
Confirmed that this is fixed in the latest release.
Thank you for reporting this.
