### ISSUE TITLE
Logical Background Images

### ISSUE THREAD

**Issue by ahmadalfy** [jonathantneal/postcss-logical#3]
According to [this draft](https://drafts.csswg.org/css-logical/#background-and-borders) I can only find references for logical values for `background-size`. I am not sure if logical properties will be added to `background-position` or not but it's really needed for rtl implementations. Do you know if such specs exist or not? If not, where do you recommend we suggest it? W3C or WHATWG?

**Comment by jonathantneal** [comment]
I don’t see references for background-size or background-position, so I won‘t go beyond the spec.
