### ISSUE TITLE
Why generating :dir selectors?

### ISSUE THREAD

**Issue by bakura10** [jonathantneal/postcss-logical#30]
Hi,

I am trying to integrate logical properties into a project of mine and would like to take advantage of a post processor. However there is something I do not get but I may be missing something obvious.

Why would:

```
.banner {
  padding-inline: 20px 40px;
}
```

generate this:

```
.banner:dir(ltr) {
  padding-left: 20px; padding-right: 40px;
}

.banner:dir(rtl) {
  padding-right: 20px; padding-left: 40px;
}
```

Instead of simply:

```
.banner {
  padding-left: 20px;
  padding-right: 40px;
  padding-inline: 20px 40px;
}
```

This would have the advantage of keeping the code much smaller and much easier to read. Modern browsers would simply use the logical properties while older browser would default to physical properties.

**Comment by ahmadalfy** [comment]
Because the output you are mentioning at the bottom doesn't satisfy both directions `ltr` and `rtl`. The `dir` pseudoclass perform that part.

**Comment by bakura10** [comment]
Hi @ahmadalfy ,

Sorry for the late reply. I tried to check but I am not sure to understand. I have did some tests and padding-inline will cover this case, no?

Let's say I have this:

![image](https://user-images.githubusercontent.com/1198915/103875662-0f22c780-5116-11eb-966a-37e2f44ce130.png)

I have a margin-left: 10px on the text to create the spacing between the icon.

If I apply a direction: rtl on the site, then it becomes like this:

![image](https://user-images.githubusercontent.com/1198915/103875783-2d88c300-5116-11eb-9693-2b39c6fa0026.png)

The margin is indeed incorrect as it is still applies on the left.

However, replacing the margin-left by margin-inline-start properly handles both the cases (ltr and rtl) without needing for any pseudo selector, and using one line only.

Could you please tell me what I am missing here?

**Comment by bakura10** [comment]
I think I got it :). Actually I misunderstood the scope of this tool and thought it was a tool used to convert non-logical properties to logical properties, while it actually took logical properties and transform them into a non-logical ones. However, if we do not plan to support IE11, many properties should actually stay in their logical form rather than being transpilled. Is this a plan improvement ? :)

**Comment by ahmadalfy** [comment]
Well I suggest you check [caniuse](https://caniuse.com/css-logical-props), seem that Safari and Edge doesn't fully support it yet like Chrome and Firefox. It's according to your needs :)

**Comment by bakura10** [comment]
Good catch... I have been tricked by the 96%, just to realize that actually this 96% is very misleading ... ! Sorry about the annoyance.

**Comment by ahmadalfy** [comment]
No worries, to be honest in my daily work I still generate the old syntax because we're still supporting wide range or browsers and it's just easy to use the plugin to generate what we need. Good luck, I will be happy to provide you with any assistance.
