### ISSUE TITLE
Does not work correctly with postcss-syntax / postcss-jsx

### ISSUE THREAD

**Issue by ackl** [jonathantneal/postcss-logical#34]
Please refer to https://github.com/ackl/postcss-logical-bug

when using jsx syntax, postcss decl.parent is defined, but decl.parent.parent is undefined, so calling parent.before throws error, need to check if parent.parent exists, else just do before on decl

pls see [this fix](https://github.com/ackl/postcss-logical/commit/4a6ceafc9a71c78384a97d0bed465098463afd13#diff-bfe9874d239014961b1ae4e89875a6155667db834a410aaaa2ebe3cf89820556R136)

**Comment by Antonio-Laguna** [comment]
This repository is getting archived. If this issue keeps happening please re-open on [@csstools/postcss-plugins](https://github.com/csstools/postcss-plugins/issues/new/choose) and we'll do our best to fix it!
