### ISSUE TITLE
Gulp plugin is generating :dir() CSS

### ISSUE THREAD

**Issue by seyedi** [jonathantneal/postcss-logical#8]
Hi, Thank you for this great tool!

Gulp plugin is generating :dir() CSS pseudo-class but that [doesn't work in chrome](https://caniuse.com/#feat=css-dir-pseudo), so how can I have it generating [dir=""] selector like your demo on [Codepen](https://codepen.io/jonneal/pen/oeZYBw)?

**Comment by ahmadalfy** [comment]
You need to add [this plugin](https://github.com/jonathantneal/postcss-dir-pseudo-class) to your list right after the logical properties one.

**Comment by seyedi** [comment]
@ahmadalfy Thanks!

**Comment by alimd** [comment]
@ahmadalfy  @jonathantneal 
Using `postcss-dir-pseudo-class` is a temporary solution.
It has been more than 5 years and there is no support for `:dir` in chromium-base browsers! ([caniuse](https://caniuse.com/#feat=css-dir-pseudo))
And I think there is no plan for it!
Isn't better to use `[dir]`?

**Comment by ahmadalfy** [comment]
@AliMD `:dir` selector is supported in Firefox and it's a part of [selectors level 4](https://www.w3.org/TR/selectors-4/#the-dir-pseudo). It's not a temporary solution, it's a matter of time till the browsers pick it up.
