### ISSUE TITLE
Viewport Units

### ISSUE THREAD

**Issue by davidf03** [jonathantneal/postcss-logical#9]
`vb` and `vi` don't seem to be supported. Will this be added?

**Comment by ahmadalfy** [comment]
If you mean [this](https://drafts.csswg.org/css-values-4/#viewport-relative-lengths) I don't really know how this can be polyfilled using CSS only.

**Comment by jonathantneal** [comment]
Depending on where it is used, we can tranform `vb` into `vh` and `vi` into `vw`, sticking it behind a query based on the orientation of the page.

**Comment by jonathantneal** [comment]
It looks like `vw` and `vh` respond to orientation changes, so it could be safe to transform `vb` and `vi` for now.

**Comment by Antonio-Laguna** [comment]
This repository is getting archived. If this issue keeps happening please re-open on [@csstools/postcss-plugins](https://github.com/csstools/postcss-plugins/issues/new/choose) and we'll do our best to fix it!
